### ISSUE TITLE
Issues with "apply selected booleans"

### ISSUE THREAD

**Issue by 0z3l07** [jayanam/jmesh-tools#25] opened 2020-06-01 11:06 UTC
v1.2.8.3
Blender 2.82.7

Hi,

1.  I placed 2 random non destructive bools. Alt+h to unhide them and then I selected one and I pressed apply selcted bool button. Ctrl+z to undo that....selected the same bool object again and this came up. It works and than it doesnt ...mhm

When this comes up it also seems to randomly applies the bools but doesnt delete the objects afterwards
![error](https://user-images.githubusercontent.com/24977832/83403837-b1a0fc80-a409-11ea-9c64-5f1d331bb431.png)

> bpy.context.scene.use_snapping = False
> bpy.context.scene.apply_bool = False
> bpy.ops.mesh.primitive_cube_add(size=2, enter_editmode=False, location=(0, 0, 0))
> bpy.ops.machin3.view_axis(axis='FRONT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.hide_view_clear()
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.ops.object.apply_bool()
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.apply_bool()
> Traceback (most recent call last):
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\fc_apply_bool_op.py", line 42, in execute
>     obj.select_set(True)
> AttributeError: 'ID' object has no attribute 'select_set'
> 
> location: <unknown location>:-1

2nd one with different primitives

> bpy.ops.mesh.primitive_cube_add(enter_editmode=False, location=(0, 0, 0))
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.hide_view_clear()
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.ops.object.delete()
> bpy.ops.object.apply_bool()
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.ops.object.delete()
> bpy.ops.object.apply_bool()
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.editmode_toggle()
> bpy.ops.mesh.select_all(action='SELECT')
> bpy.ops.mesh.remove_doubles()
> bpy.ops.object.editmode_toggle()
> bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='MEDIAN')
> bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.hide_view_clear()
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.ops.object.delete()
> bpy.ops.object.apply_bool()
> bpy.ops.object.modifier_apply(modifier="FC_BOOL")
> bpy.ops.object.modifier_apply(modifier="FC_BOOL.001")
> bpy.ops.object.select_all(action='DESELECT')
> bpy.ops.object.delete()
> bpy.ops.object.apply_bool()
> Traceback (most recent call last):
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\jmesh-tools-master\fc_apply_bool_op.py", line 42, in execute
>     obj.select_set(True)
> AttributeError: 'ID' object has no attribute 'select_set'
> 
> location: <unknown location>:-1

**Comment by jayanam** [comment] 2020-06-01 11:24
Could you try with the latest version, I just tried to reproduce but cant

**Comment by 0z3l07** [comment] 2020-06-01 12:05
Cutting into the mesh hard crashes jmesh on 2.83 (june 1)
The ctrl + left click when you have created a blue outline
It creates the modifier and pending collection but jmesh crashed completly like the workspace error

> Traceback (most recent call last):
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jmesh-tools-master\fc_primitive_mode_op.py", line 224, in modal
>     self.create_object(context)
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jmesh-tools-master\fc_primitive_mode_op.py", line 353, in create_object
>     self.create_mesh(context)
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jmesh-tools-master\fc_primitive_mode_op.py", line 515, in create_mesh
>     bpy.ops.object.mode_set(mode=self.current_mode)
>   File "E:\blender-2.83.0-ec26260132b4-windows64\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
>     ret = op_call(self.idname_py(), None, kw)
> RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect
> 
> location: <unknown location>:-1

same on 2.9 ..... *confused*

**Comment by jayanam** [comment] 2020-06-01 12:10
Did you change the workspace? Which mode are you in? Edit mode? I
cant reproduce this

**Comment by 0z3l07** [comment] 2020-06-01 12:11
Yeah deleted this by accident. 

crashes completely on 2.83 and 2.9

> Traceback (most recent call last):
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jmesh-tools-master\fc_primitive_mode_op.py", line 224, in modal
>     self.create_object(context)
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jmesh-tools-master\fc_primitive_mode_op.py", line 353, in create_object
>     self.create_mesh(context)
>   File "C:\Users\\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\jmesh-tools-master\fc_primitive_mode_op.py", line 515, in create_mesh
>     bpy.ops.object.mode_set(mode=self.current_mode)
>   File "E:\blender-2.83.0-ec26260132b4-windows64\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
>     ret = op_call(self.idname_py(), None, kw)
> RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect
> 
> location: <unknown location>:-1

**Comment by 0z3l07** [comment] 2020-06-01 12:13
No, layout and object mode

**Comment by 0z3l07** [comment] 2020-06-01 13:19
I can easily reproduce this crashing on 2.83 and above on my other systems ...mhm
win 10 64bit , blender never ever run on them

**Comment by 0z3l07** [comment] 2020-06-01 16:54
unlisted videos of 2.83 and 2.9 crashing

https://youtu.be/zOT8FdWj4so

https://youtu.be/uW0D6sfKerg

**Comment by jayanam** [comment] 2020-06-01 18:11
Thx, this one I cant reproduce.

**Comment by 0z3l07** [comment] 2020-06-01 18:31
mhm very strange.... the destructive worksflow seems to be fine on 2.82+

**Comment by jayanam** [comment] 2020-06-01 19:15
Strange.. can you try, either with 2.9 or 2.83 to deinstall the addon, then
restart blender and install again.

**Comment by 0z3l07** [comment] 2020-06-01 19:34
yep have done this countless times...same error.
Could it be your python version compared to mine?

**Comment by jayanam** [comment] 2020-06-01 19:46
I rewrote the algorithm, wasnt bulletproof:-) Please try 1.2.8.5, just
uploaded

**Comment by jayanam** [comment] 2020-06-01 19:49
This one I still cant reproduce, fixed the Apply All booleans.

**Comment by 0z3l07** [comment] 2020-06-01 19:54
2.83+ still crashes
Hasnt changed anything for me :(
Even on 2.82 it still doesnt work on "apply all"

**Comment by jayanam** [comment] 2020-06-01 19:58
Can finally reproduce on latest 2.90, will test

**Comment by jayanam** [comment] 2020-06-01 20:15
I found it, behavior is different then in the early 2.90 version:-) Fixed in 1.2.8.6 please try

**Comment by 0z3l07** [comment] 2020-06-01 20:41
2.82
From my initial testing ...selected/all boolean operations work flawlessly even when you ctrl+z and back n forth. I dont want to celebrate but I couldnt break it so far 👍 Even double selecting bools and applying selected works as intended 

2.83+
Same results. Stable af so far :)

Youve earned yourself a new patreon.....although thats a pretty bad hourly wage ;)

**Comment by jayanam** [comment] 2020-06-01 20:44
Hey great, then Im closing the issue:-)

> Youve earned yourself a new patreon.....although thats a pretty bad hourly wage ;)
I dont care too much for this:-) But thx a lot anyway.

**Closed by jayanam** 2020-06-01 20:44 UTC
